// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPositions(arg1, arg2) {
  return window['go']['main']['App']['GetPositions'](arg1, arg2);
}

export function GreetName(arg1) {
  return window['go']['main']['App']['GreetName'](arg1);
}
