// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBasics(arg1, arg2) {
  return window['go']['main']['App']['GetBasics'](arg1, arg2);
}

export function GetCombinations(arg1, arg2) {
  return window['go']['main']['App']['GetCombinations'](arg1, arg2);
}

export function GetPatterns(arg1, arg2) {
  return window['go']['main']['App']['GetPatterns'](arg1, arg2);
}

export function GetPositions(arg1, arg2) {
  return window['go']['main']['App']['GetPositions'](arg1, arg2);
}

export function GetVocab(arg1, arg2) {
  return window['go']['main']['App']['GetVocab'](arg1, arg2);
}
