// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPositions(arg1:number,arg2:number):Promise<string>;

export function GetShines(arg1:number,arg2:number):Promise<string>;
